### ISSUE TITLE
CaptureEditFrame saves accelerometer data twice

### ISSUE THREAD

**Issue by Tenchi2xh** [heig-iict-ida/shimmer_move_analyzer#1]
The [CaptureEditFrame](https://github.com/heig-iict-ida/shimmer_move_analyzer/blob/master/src/madsdf/shimmer/gui/CaptureEditFrame.java) class that writes results to a file saves the accelerometer data twice, with no gyro data. Since the gyro data is displayed in the graphs, the data exists and should be saved.

**Comment by julienr** [comment]
Branch fix_gyro_save should fix this issues, can you confirm ?

**Comment by Tenchi2xh** [comment]
Sadly we only had a few hours in class to capture movements with the Shimmers and I won't have acces to them anymore for further testing. Acceleration data was sufficient for our project but I just wanted to point out the missing gyro. Thank you anyway for the quick fix!

**Comment by julienr** [comment]
Ok, I'll test it later. Thanks for the report
